block_labels = ["needs-decision"]
delete_merged_branches = true
required_approvals = 1
status = [
  "test (stable, x86_64-unknown-linux-gnu)",
  "test (stable, thumbv6m-none-eabi)",
  "test (stable, thumbv7m-none-eabi)",
  "test (1.54.0, x86_64-unknown-linux-gnu)",
  "test (1.54.0, thumbv6m-none-eabi)",
  "test (1.54.0, thumbv7m-none-eabi)",
  "test (nightly, x86_64-unknown-linux-gnu)",
  "test (nightly, thumbv6m-none-eabi)",
  "test (nightly, thumbv7m-none-eabi)",
  "fmt",
]
