# CI moves this file to `Cargo.toml` when building for stable.

[workspace]
resolver = "2"

members = [
    "embedded-hal",
    "embedded-hal-nb",
    "embedded-hal-bus",
    "embedded-can",
    "embedded-io",
    "embedded-io-adapters",
]

# Cargo implicitly adds path dependencies to the workspace.
# Even if they're optional and not enabled. This prevents that.
exclude = [
    "embedded-hal-async",
    "embedded-io-async",
]