on:
  push:
    branches: [ staging, trying, master ]
  pull_request:

name: CI Bus

env:
  RUSTFLAGS: '--deny warnings'

jobs:
  ci-linux-bus:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [nightly]
        TARGET: [x86_64-unknown-linux-gnu, thumbv6m-none-eabi, thumbv7m-none-eabi]

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.TARGET }}
          override: true
      - run: cargo check --target=${{ matrix.TARGET }}
        working-directory: embedded-hal-bus

      - run: cargo test --target=${{ matrix.TARGET }}
        if: contains(matrix.TARGET, 'linux')
        working-directory: embedded-hal-bus
