on:
  push:
    branches: [ staging, trying, master ]
  pull_request:

name: Clippy check
jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          # embedded-hal-async needs nightly.
          # Use a pinned version to avoid spontaneous breakages (new clippy lints are added often)
          toolchain: nightly-2022-11-22
          components: clippy
      - run: cargo clippy -- --deny=warnings