on:
  push:
    branches: [ staging, trying, master ]
  pull_request:

name: Continuous integration

env:
  RUSTFLAGS: '--deny warnings'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # All generated code should be running on stable now
        rust:
          - stable
          - 1.59.0  # MSRV
          - nightly

        # The default target we're compiling on and for
        target:
          - x86_64-unknown-linux-gnu
          - thumbv6m-none-eabi
          - thumbv7m-none-eabi

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}

      - run: sed -i '/nightly-only/d' Cargo.toml 
        if: matrix.rust != 'nightly'

      - run: cargo check --target=${{ matrix.target }}

      - run: cargo test --target=${{ matrix.target }}
        if: contains(matrix.target, 'linux')
